[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = {version = "1.6.0",features = ["serde"]}
ferris-says = "0.3.1"
secure-password = "0.3.1"
serde_json = "1.0.117"
